### ISSUE TITLE
Maven build issue : jxgrabkey

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-executor#1]
Hello,

I'm facing an issue with building the application linked with one of its dependency: **jxgrabkey**

Maven output for `mvn clean install` (using maven 3.6.3):

`[ERROR] Failed to execute goal on project cerberus-executor: Could not resolve dependencies for project org.cerberus:cerberus-executor:jar:1.1.0: Could not find artifact jxgrabkey:jxgrabkey:jar:1.0 in spring-releases (https://repo.spring.io/libs-release) -> [Help 1]
`

According to this [thread](https://stackoverflow.com/questions/45103410/the-pom-for-jxgrabkeyjxgrabkeyjar1-0-is-missing-no-dependency-information-av), it seems that the repository doesn't exist anymore on spring side.

Am I missing something?
Can you provide in the release section an already deployed .jar?
Thanks

**Comment by bcivel** [comment]
Hello,
I'm going to push a change excluding this dependency.
Thanks

**Comment by Nouxx** [comment]
Thanks !

**Comment by bcivel** [comment]
Should be ok now.

**Comment by Nouxx** [comment]
Yup, thanks a lot!
